# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
header = "# Changelog\n\n"

body = """
{% if version %}\
    # {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%d %B %Y") }}
    {% for group, commits in commits | group_by(attribute="group") %}
        ## {{ group | striptags | trim | upper_first }}
        {% for commit in commits %}
        * {{ commit.message | upper_first }}{% if commit.metadata.issue %} (#{{ commit.metadata.issue }}){% endif %}\
        {% endfor %}
    {% endfor %}
{% endif %}
"""

trim = true

render_always = false

[git]
conventional_commits = true

filter_unconventional = false

commit_parsers = [
    # https://git-cliff.org/docs/tips-and-tricks#changing-the-group-order
    { message = "^[a-z]*!:", group = "<!-- 0 -->Breaking Changes" },
    { message = "^feat", group = "<!-- 1 -->Features" },
    { message = "^fix", group = "<!-- 2 -->Fixes" },
    { message = "^docs", group = "<!-- 3 -->Documentation" },
    { message = "^test", group = "<!-- 4 -->Tests" },
    { message = "^refactor", group = "<!-- 5 -->Refactoring" },
    { message = "^ci", group = "<!-- 6 -->CI" },
    { message = "^chore", skip = true },
]

filter_commits = false

fail_on_unmatched_commit = false
